name: hello world
on:
  push:
    branches: [ unittest ]

jobs:
  hello_world:
  runs-on: ubuntu-latest
  steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - uses: actions/setup-pyton@v4 
        with:
          pyton-version: '3.10'

      - run: pip install -r requirements.txt

      - run: pyton main_test.py